services:
  - type: web
    name: cricket-live-backend
    runtime: node
    region: oregon
    buildCommand: cd backend && yarn install && yarn build
    startCommand: cd backend && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: STATPAL_KEY
        sync: false
