services:
  - type: web
    name: cricket-live-backend
    runtime: node
    region: oregon
    rootDir: backend
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: STATPAL_KEY
        sync: false
